import Sidebar from '@/components/Sidebar'
import clsx from 'clsx'
import styles from '@/styles/Beam.module.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function ServerLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <section className='fixed flex w-screen'>

            {children}
        </section>
    );
}