import Sidebar from "@/components/Sidebar";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function CreateServerLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <section className='fixed flex w-screen'>
            {/*  @ts-expect-error Server Component */}
            <Sidebar />
            {children}
        </section>
    );
}