import clsx from 'clsx'
import styles from '@/styles/Beam.module.css'
import ServerSidebar from '@/components/server/ServerSidebar';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function ServerIdLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <section >

            {/* <ServerSidebar /> */}
            {children}
        </section>
    );
}